services:
    kasimi.markreadconfirm.listener:
        class: 'kasimi\markreadconfirm\event\listener'
        arguments:
            - '@language'
            - '@template'
        tags:
            - { name: 'event.listener' }
